export const TEAM_FLAGS: Record<string, string> = {
  'France': '🇫🇷',
  'Spain': '🇪🇸',
  'Argentina': '🇦🇷',
  'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Portugal': '🇵🇹',
  'Brazil': '🇧🇷',
  'Netherlands': '🇳🇱',
  'Morocco': '🇲🇦',
  'Belgium': '🇧🇪',
  'Germany': '🇩🇪',
  'Croatia': '🇭🇷',
  'Italy': '🇮🇹',
  'Colombia': '🇨🇴',
  'Senegal': '🇸🇳',
  'Mexico': '🇲🇽',
  'USA': '🇺🇸',
  'Uruguay': '🇺🇾',
  'Japan': '🇯🇵',
  'Switzerland': '🇨🇭',
  'Denmark': '🇩🇰',
  'IR Iran': '🇮🇷',
  'Iran': '🇮🇷',
  'Türkiye': '🇹🇷',
  'Ecuador': '🇪🇨',
  'Austria': '🇦🇹',
  'Korea Republic': '🇰🇷',
  'South Korea': '🇰🇷',
  'Nigeria': '🇳🇬',
  'Australia': '🇦🇺',
  'Algeria': '🇩🇿',
  'Egypt': '🇪🇬',
  'Canada': '🇨🇦',
  'Norway': '🇳🇴',
  'Ukraine': '🇺🇦',
  'Panama': '🇵🇦',
  'Côte d\'Ivoire': '🇨🇮',
  'Poland': '🇵🇱',
  'Sweden': '🇸🇪',
  'Paraguay': '🇵🇾',
  'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Tunisia': '🇹🇳',
  'Cameroon': '🇨🇲',
  'Congo DR': '🇨🇩',
  'Uzbekistan': '🇺🇿',
  'Costa Rica': '🇨🇷',
  'Mali': '🇲🇱',
  'Chile': '🇨🇱',
  'Qatar': '🇶🇦',
  'Iraq': '🇮🇶',
  'South Africa': '🇿🇦',
  'Saudi Arabia': '🇸🇦',
  'Jordan': '🇯🇴',
  'Bosnia and Herzegovina': '🇧🇦',
  'Honduras': '🇭🇳',
  'Cabo Verde': '🇨🇻',
  'Jamaica': '🇯🇲',
  'Ghana': '🇬🇭',
  'Curaçao': '🇨🇼',
  'Haiti': '🇭🇹',
  'New Zealand': '🇳🇿',
  'Czechia': '🇨🇿'
};

export const getFlagEmoji = (teamName: string): string => {
  if (!teamName) return '⚽';
  const trimmed = teamName.trim();
  return TEAM_FLAGS[trimmed] || TEAM_FLAGS[teamName] || '⚽';
};
